### ISSUE TITLE
Git diff dots, compare from where it diverged

### ISSUE THREAD

**Issue by tjj225** [roopakv/orbs#47]
Hello Roopak 

Thank you for this great orb.

I think it would be useful to have 3 dots for the git diffs.
https://matthew-brett.github.io/pydagogue/git_diff_dots.html

My use case is I don't want to trigger my develop branch due to a commit change F or G as in example above.  

Using version
swissknife: roopakv/swissknife@0.37.0

**Comment by roopakv** [comment]
@tjj225 which command in specific are you referring to? 

most commands have a `use-divergence-point` option which effectively does what you are saying. Let me know if that doesn't solve your issue.

but TIL that I could have used `...` instead of the complex way I do it now :D

**Comment by tjj225** [comment]
Hello Roopak

Thank you,  I am using run_if_modified 

use-divergence-point: true 


This works!
