### ISSUE TITLE
grep needs -P to accept regex with lookahead

### ISSUE THREAD

**Issue by amerkay** [roopakv/orbs#48]
Great work. 

I'm trying to use your orb, but my use case needs negative lookahead in regex, which needs -P to be added to the `grep` command. See https://stackoverflow.com/a/9198987.

Keep it up :)

**Comment by roopakv** [comment]
hey @amerkay thank you for the note. Is there a specific command you'd like to use this for? 

to potentially not break current users would you be ok if the -P flag is option to the command?

**Comment by amerkay** [comment]
Hi, Thanks for the quick reply!

I'm trying to exclude a the /static folder from `run_frontend_workflow`, but process it using `run_static_workflow` only if the files in it change. It works if the -P is included to perform perl regex, which allows for negative lookahead. 

```
code-param-name-map: '
    [
    {"regex": "^frontend(?!\/static).*", "param_name": "run_frontend_workflow"},
    {"regex": "^(frontend\/static).*", "param_name": "run_static_workflow"}
    ]'
```

So, yes, if you include it as an option, that'll solve my problem :)

**Comment by roopakv** [comment]
@amerkay you can use the perl search mode in [v0.40.0](https://circleci.com/orbs/registry/orb/roopakv/swissknife) of swissknife for negative lookahead. It does require Perl to be installed but I think this is generally available on most Linux installs.

let me know if this doesn't work for you.

**Comment by amerkay** [comment]
Hey! That's fantastic. Thank you. I'll give it a try next few days and report back if there are any issues :)
