### ISSUE TITLE
Incorrect jq usage in append_string_to_params

### ISSUE THREAD

**Issue by noisyscanner** [roopakv/orbs#55]
Hey, super useful orb - thank you! We are hoping that `trigger-workflows-for-all-modified` will substantially speed up our CI and bring the cost down.

When using the above step, it fails with the following error: 
![image](https://user-images.githubusercontent.com/627654/85699692-a624b680-b6d3-11ea-8309-040e5331d327.png)

I copied the source of this into our pipeline and added `set -x` for debugging - it looks like `jq -cr` is the culprit. Trying this locally I got the same error and it seems that `jq -cr ''` is correct if you want to redirect the output to a file. I will put in a PR to fix this.

**Comment by roopakv** [comment]
@noisyscanner what version of jq are you using? Because I know this command is being used by at least pipelines with no issues. Maybe I should also check for versions in the beginning part of the script

**Comment by roopakv** [comment]
Hmm we are on the same version of jq `jq-1.5-1-a5b5cbe`

Could you paste a code snippet of how you are calling the orb. I remember running into this myself. It was weirdness with jq I think.

**Comment by noisyscanner** [comment]
That was a quick response! Locally I installed the same version as you mention, and dry-ran it through as you see in the commands echoed above, and got the same issue. Adding the quote after like `jq -cr ''` fixed it for me:

![image](https://user-images.githubusercontent.com/627654/85702924-c86c0380-b6d6-11ea-810f-163382bd8503.png)

**Comment by noisyscanner** [comment]
@roopakv the command you posted also worked fine for my, but try appending `> file` to the end - then I get the error

**Comment by roopakv** [comment]
@noisyscanner all right lets give it a shot, send me a PR.

I'll have to make sure it works on the sample repo and some internal repos. as long it does we should be good :)

**Comment by roopakv** [comment]
you are right, the command files when adding `> file`. However im so confused. We are using this daily, and no pipelines are failing 🤷 

oh wells! thanks for the catch

**Comment by roopakv** [comment]
@noisyscanner published. you should be able to use version `0.44.0` with the fix.

You should see the latest version at https://orb.swissknife.dev

thanks for the fix :)
