### ISSUE TITLE
Control the start order of parallel jobs - possible?

### ISSUE THREAD

**Issue by wlad** [roopakv/orbs#69]
Hi, 

I've posted a detailed [question on circleci's issue tracker](https://github.com/circleci/circleci-docs/issues/4688) about the start/run order of parallel jobs.

Is it something SK orb could handle?

**Comment by wlad** [comment]
I think it's not possible to controll the order of concurrent job's start. But since jobs has a know state as documented [here](https://circleci.com/docs/2.0/workflows/#states) I may be possible to create a `wait_for_job_running_state` step(?)

**Comment by roopakv** [comment]
@wlad the [wait for job](https://circleci.com/orbs/registry/orb/roopakv/swissknife#commands-wait_for_job) command in swissknife lets you wait for a job in the same workflow. This might be a quick fix for you.

Please re-open if this does not work for you
