### ISSUE TITLE
Triggering Forked Pull Requests Pipeline

### ISSUE THREAD

**Issue by twslade** [roopakv/orbs#71]
Thanks for the great tool!

I'm seeing an issue trying to trigger builds for a pull request from a trusted fork. I've looked through the orb code and I'm seeing an issue with the branch name reference for the pipeline trigger.

https://github.com/roopakv/orbs/blob/6c8ff9d25521ed2f365ea63c723d3e1250e894cf/src/commands/trigger_pipeline_if_modified.yml#L54-L63

The branch I am trying to trigger is `pull/610`. 

The response I get is `Branch not found.`.

In the circle docs for [triggering a pipeline](https://circleci.com/docs/api/v2/#operation/triggerPipeline) they mention the following:

> The branch where the pipeline ran. The `HEAD` commit on this branch was used for the pipeline. Note that branch and tag are mutually exclusive. To trigger a pipeline for a PR by number use `pull/<number>/head` for the PR ref or `pull/<number>/merge` for the merge ref (GitHub only).

I can trigger the build using the syntax:

```sh
curl --silent -X POST     "https://circleci.com/api/v2/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pipeline?circle-token=${CIRCLE_TOKEN}"     
  -H 'Accept: */*'     
  -H 'Content-Type: application/json'     
  -d '{
        "branch": "'pull/610/head'",
        "parameters": '$custom_params'
    }
```
 
Is this something that can be added to this orb or should I look into doing some env modification before triggering the build?

**Comment by roopakv** [comment]
your PR looks good. lets just use the newer env vars adn we should be good to go :)
