### ISSUE TITLE
trigger-pipeline command doesn't work for tags

### ISSUE THREAD

**Issue by russelltaga** [roopakv/orbs#89]
Hello!

When invoking the `trigger-pipeline` command for a `tag` seeing an error like:

```
----------------------------------------
Triggering Pipeline
{
  "message" : "Invalid input"
}Finished triggering pipeline
----------------------------------------
CircleCI received exit code 0
```

In this scenario, `CIRCLE_BRANCH` is blank and `CIRCLE_TAG` is set to the value of the git tag.

Think we can fix this with some slight modifications here to add `tag` to the body of the [CircleCI API call](https://circleci.com/docs/api/v2/?section=reference#operation/triggerPipeline).

https://github.com/roopakv/orbs/blob/master/scripts/trigger-pipeline.sh#L25

If you agree, we can post a PR

**Comment by roopakv** [comment]
@russelltaga that works. since mutually exclusive you will need need to make sure we add either branch or tag, but that should be fairly simple. 

Let me know if you can make a PR. if not I am happy to give it a shot

**Comment by russelltaga** [comment]
@roopakv forked and created this PR

https://github.com/roopakv/orbs/pull/90

**Comment by russelltaga** [comment]
@roopakv there was a bug with that last PR, here's a follow up with the fix

https://github.com/roopakv/orbs/pull/91
